<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="1" ignored="0" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="FREE CRM Application Test Automation Test Suite" duration-ms="30327" started-at="2019-02-01T09:02:26Z" finished-at="2019-02-01T09:02:56Z">
    <groups>
    </groups>
    <test name="Free CRM App Test Cases" duration-ms="30327" started-at="2019-02-01T09:02:26Z" finished-at="2019-02-01T09:02:56Z">
      <class name="com.crm.qa.testcases.STLoginPageTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.crm.qa.testcases.STLoginPageTest@598067a5]" name="setUp" is-config="true" duration-ms="9393" started-at="2019-02-01T14:32:26Z" finished-at="2019-02-01T14:32:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="SKIP" signature="stLoginPageTestTitle()[pri:0, instance:com.crm.qa.testcases.STLoginPageTest@598067a5]" name="stLoginPageTestTitle" duration-ms="193" started-at="2019-02-01T14:32:35Z" finished-at="2019-02-01T14:32:35Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Smart Track] but found [Coupa CW]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Smart Track] but found [Coupa CW]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at com.crm.qa.testcases.STLoginPageTest.stLoginPageTestTitle(STLoginPageTest.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- stLoginPageTestTitle -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.crm.qa.testcases.STLoginPageTest@598067a5]" name="setUp" is-config="true" duration-ms="8821" started-at="2019-02-01T14:32:36Z" finished-at="2019-02-01T14:32:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.crm.qa.testcases.STLoginPageTest@598067a5]" name="tearDown" is-config="true" duration-ms="0" started-at="2019-02-01T14:32:36Z" finished-at="2019-02-01T14:32:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="FAIL" signature="stLoginPageTestTitle()[pri:0, instance:com.crm.qa.testcases.STLoginPageTest@598067a5]" name="stLoginPageTestTitle" duration-ms="16" started-at="2019-02-01T14:32:44Z" finished-at="2019-02-01T14:32:44Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Smart Track] but found [Coupa CW]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Smart Track] but found [Coupa CW]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at com.crm.qa.testcases.STLoginPageTest.stLoginPageTestTitle(STLoginPageTest.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1014)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1215)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- stLoginPageTestTitle -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.crm.qa.testcases.STLoginPageTest@598067a5]" name="tearDown" is-config="true" duration-ms="0" started-at="2019-02-01T14:32:46Z" finished-at="2019-02-01T14:32:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.crm.qa.testcases.STLoginPageTest@598067a5]" name="setUp" is-config="true" duration-ms="9065" started-at="2019-02-01T14:32:46Z" finished-at="2019-02-01T14:32:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="stLoginTest()[pri:0, instance:com.crm.qa.testcases.STLoginPageTest@598067a5]" name="stLoginTest" duration-ms="1367" started-at="2019-02-01T14:32:55Z" finished-at="2019-02-01T14:32:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- stLoginTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.crm.qa.testcases.STLoginPageTest@598067a5]" name="tearDown" is-config="true" duration-ms="0" started-at="2019-02-01T14:32:56Z" finished-at="2019-02-01T14:32:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.crm.qa.testcases.STLoginPageTest -->
    </test> <!-- Free CRM App Test Cases -->
  </suite> <!-- FREE CRM Application Test Automation Test Suite -->
</testng-results>
